#!/usr/bin/env perl

# Plugin de IV para facilitar algunas cosas en la asignatura.
# Instalación:
# Prerrequisitos: Perl y git instalados (Perl estará instalado en cualquier Linux)
# > cd ~/bin # O cualquier otro directorio en el path de ejecución
# > wget https://raw.githubusercontent.com/JJ/IV/master/scripts/git-iv #O bajar el URL a ese directorio de cualquier otra manera
# > chmod +x git-iv
# Ya se puede usar a continuación. Por ejemplo
# > git iv # Para imprimir los subcomandos

use strict;
use warnings;
use Git;

use v5.14;

my @subcommands = qw(objetivo sube-objetivo);

die( print_usage() ) unless @ARGV;
my $subcommand = shift;

die "No se reconoce el subcomando $subcommand" unless grep( /\b$subcommand\b/, @subcommands );

my $repo = Git->repository (Directory => '.');

my @args = @ARGV;
die( print_usage ()) if  $args[0] eq '--help'  ;

if ( $subcommand eq "objetivo" ) {
  $repo->command( "checkout", "-b", "Objetivo-" . $args[0]);
}

if ( $subcommand eq "sube-objetivo" ) {
  my $branch = $repo->command( "rev-parse", "--abbrev-ref", "HEAD" );
  chomp($branch);
  $repo->command ( "push", "-u", "origin", $branch );
}

sub print_usage {
    return <<EOC;
Uso:
    git iv objetivo <número> -- crea una rama para ese objetivo
    git iv sube-objetivo          -- sube al repo remoto la rama

    git iv subcomando --help -- imprime este mensaje
EOC
}
