user "root"; 

group fiware => "130.206.127.211";

desc "Install git";
task "git", group => "fiware", sub {
    install "git";
};

desc "Install docker";
task "docker", group => "fiware", sub {
   install "docker.io";
};

desc "Install nodejs";
task "nodejs", group => "fiware", sub {
   install "nodejs";
};
