# -*- mode: ruby -*- 
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos65"

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "emacs"
  end

end
