name: Yaml Lint
on:
  push:
    paths:
      - "**/*.ya?ml"
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Comprueba yaml
        run: yq eval .github/workflows/*.yml
