name: Yaml Lint
on:
  push:
    paths:
      - "**/*.ya?ml"
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
